# Generated by Django 4.2.1 on 2023-05-23 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date', models.DateField(default=datetime.date(1111, 1, 1))),
                ('author', models.CharField(default="author's name", max_length=100)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('topic', models.CharField(max_length=200)),
                ('first_sentence', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('Treatment', 'Treatment'), ('Make up', 'Make up'), ('Manicure', 'Manicure')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
