# Generated by Django 4.2.1 on 2023-06-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izada', '0002_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
